name: "Terraform destroy"

on:
  push:
    branches:
      - destroy

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: Setup terraform variables
        id: vars
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          access_key="${{secrets.ACCESS_KEY}}"
          secret_key= "${{secrets.SECRET_KEY}}"
          db_username="${{secrets.DB_USERNAME}}"
          db_password="${{secrets.DB_PASSWORD}}"
          environment="${{vars.ENVIRONMENT}}"
          region="${{vars.REGION}}"
          EOF

      - name: Terraform Format
        id: fmt
        run: terraform fmt
      
      - name: Terraform Format check
        id: fmtcheck
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/destroy' && github.event_name == 'push'
        run: terraform destroy -auto-approve -input=false
